## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly

coveralls: true

before_install:
  - julia -e 'import Pkg; Pkg.pkg"add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/Seis.jl"'
  